version: '3.7'
services:
  db:
    build:
        context: ./bankingapp
        dockerfile: Dockerfile.postgres
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking_db
    volumes:
      - ./bankingapp/sql/Create_tables.sql:/docker-entrypoint-initdb.d/Create_tables.sql
      - ./bankingapp/sql/Generate_data.sql:/docker-entrypoint-initdb.d/Generate_data.sql
  backend:
    build:
        context: ./bankingapp
        dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    depends_on:
      - backend
